project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd 
      - index_pubs.qmd
format:
  html:
    theme: cosmo
    css: styles.css



