project:
  type: website

website:
  navbar:
    background: "#800000"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Publications"
        file: index_pubs.qmd
      - text: "Who Are We?"
        file: ContactUs.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: nord



